const {
  withAndroidManifest,
  withDangerousMod,
  AndroidConfig,
} = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Let the app trust a SmartZone controller whose certificate an operator has
 * installed on the device.
 *
 * Almost every SmartZone cluster answers on a self-signed certificate, and
 * that is the single most common reason a controller app fails on first run.
 * There are two honest ways out, and this plugin implements the safe one.
 *
 *   Android: since API 24 an app ignores user-installed CAs unless it says
 *   otherwise. This plugin writes a network security config that trusts the
 *   system store *and* the user store, so an operator who installs the
 *   controller's certificate under Settings → Security → Encryption &
 *   credentials gets a working, verified TLS connection.
 *
 *   iOS: `Info.plist` cannot make the system trust an unknown certificate —
 *   App Transport Security exceptions relax the cipher and version policy,
 *   not the trust evaluation. The operator installs the controller's
 *   certificate as a configuration profile and enables it under Settings →
 *   General → About → Certificate Trust Settings. Nothing to configure in
 *   the build, so this plugin leaves iOS alone.
 *
 * What this plugin deliberately does not do is disable certificate checking.
 * An app that manages an entire wireless estate is exactly the app that
 * should not accept any certificate presented to it: the credentials it
 * carries are the whole network.
 */

const NETWORK_SECURITY_CONFIG = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by plugins/withControllerTrust.js. Edit the plugin, not this file.

  Trusts the system CA store plus any certificate the operator has installed
  on the device, which is how a self-signed SmartZone controller is reached
  without weakening TLS for anything else.
-->
<network-security-config>
    <base-config cleartextTrafficPermitted="false">
        <trust-anchors>
            <certificates src="system" />
            <certificates src="user" />
        </trust-anchors>
    </base-config>
</network-security-config>
`;

const withNetworkSecurityConfigFile = (config) =>
  withDangerousMod(config, [
    'android',
    async (cfg) => {
      const xmlDir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'res',
        'xml',
      );
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(
        path.join(xmlDir, 'network_security_config.xml'),
        NETWORK_SECURITY_CONFIG,
        'utf8',
      );
      return cfg;
    },
  ]);

const withManifestReference = (config) =>
  withAndroidManifest(config, (cfg) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(
      cfg.modResults,
    );
    application.$['android:networkSecurityConfig'] =
      '@xml/network_security_config';
    // The controller is reached over HTTPS only; saying so keeps an
    // accidental http:// URL from silently working in a debug build.
    application.$['android:usesCleartextTraffic'] = 'false';
    return cfg;
  });

module.exports = function withControllerTrust(config) {
  return withManifestReference(withNetworkSecurityConfigFile(config));
};
